language: csharp
mono: none
dotnet: 3.1
branches:
  only:
  - master
install:
 - dotnet restore
script:
 - dotnet build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push artsdatabanken/nin-kode-api:latest;
    fi
  - ./deploy.sh