language: csharp
mono: none
dotnet: 3.1
branches:
  only:
  - master
install:
 - dotnet restore
script:
<<<<<<< HEAD
 - dotnet build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push artsdatabanken/nin-kode-api:latest;
    fi






=======
 - dotnet build
>>>>>>> 7dff21d77c2501e1c2d9dbd7259fbf20fad25f13
