language: csharp
mono: none
dotnet: 6.0
branches:
  only:
  - master
install:
 - dotnet restore
script:
 - docker build -f Dockerfile --force-rm -t artsdatabanken/nin-kode-api .
 - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST, BRANCH=$BRANCH"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push artsdatabanken/nin-kode-api:latest;
    fi
  - ./deploy.sh $slackaddy
