# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - staging
    exclude:
      - master
      - main
  paths:
    exclude:
      - README.md
      
resources:
- repo: self
  lfs: true

variables:
  tag: 'staging'

jobs:
- job: FetchLFSFiles
  displayName: Fetch LFS files
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: CmdLine@2
    displayName: Fetch LFS files
    inputs:
      script: |
        git lfs version
        git lfs fetch origin --all
        ls -l NinKode.WebApi/databases
        git lfs status

- job: BuildAndPublish
  displayName: Build and publish Docker image
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'Dockerhub'
      repository: 'artsdatabanken/nin-kode-api'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(tag)'
  - task: Docker@2
    displayName: Publish image
    inputs:
      containerRegistry: 'Dockerhub'
      repository: 'artsdatabanken/nin-kode-api'
      command: 'push'
      tags: '$(tag)'
