# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - staging
    exclude:
      - master
      - main
  paths:
    exclude:
      - README.md
      
steps:
- checkout: self
  lfs: true

- script: |
   git lfs fetch
   git lfs pull
  displayName: git-lfs

variables:
  tag: 'staging'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'artsdatabanken/nin-kode-api'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Publish image
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 'artsdatabanken/nin-kode-api'
        command: 'push'
        tags: '$(tag)'

