# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - staging
    exclude:
      - master
      - main
  paths:
    exclude:
      - README.md
      
variables:
  tag: 'staging'

jobs:
- job: BuildAndPublish
  displayName: Build and publish Docker image
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    lfs: true
  - task: Docker@2
    displayName: Build an image
    inputs:
      containerRegistry: 'Dockerhub'
      repository: 'artsdatabanken/nin-kode-api'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: '$(tag)'
  - task: Docker@2
    displayName: Publish image
    inputs:
      containerRegistry: 'Dockerhub'
      repository: 'artsdatabanken/nin-kode-api'
      command: 'push'
      tags: '$(tag)'
