// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiN.Database;

namespace NiN.Database.Migrations
{
    [DbContext(typeof(NiNContext))]
    [Migration("20210921131032_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NiN.Database.Models.Basistrinn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LKMKodeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LKMKodeId");

                    b.ToTable("Basistrinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Grunntype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.ToTable("Grunntype");
                });

            modelBuilder.Entity("NiN.Database.Models.GrunntypeKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GrunntypeId")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KodeName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("GrunntypeId")
                        .IsUnique();

                    b.ToTable("GrunntypeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypegruppeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypegruppeId");

                    b.ToTable("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.HovedtypeKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HovedtypeKeyId")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KodeName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeKeyId")
                        .IsUnique();

                    b.ToTable("HovedtypeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtypegruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NatursystemId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NatursystemId");

                    b.ToTable("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN.Database.Models.HovedtypegruppeKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HovedtypegruppeId")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KodeName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypegruppeId")
                        .IsUnique();

                    b.ToTable("HovedtypegruppeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Kartleggingsenhet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<string>("KodeId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Malestokk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.ToTable("Kartleggingsenhet");
                });

            modelBuilder.Entity("NiN.Database.Models.LKMKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KodeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LKMKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Miljovariabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<string>("Kode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LkmKategori")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.ToTable("Miljovariabel");
                });

            modelBuilder.Entity("NiN.Database.Models.Natursystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Natursystem");
                });

            modelBuilder.Entity("NiN.Database.Models.NatursystemKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KodeName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NatursystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NatursystemId")
                        .IsUnique();

                    b.ToTable("NatursystemKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Trinn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KodeId")
                        .HasColumnType("int");

                    b.Property<int?>("MiljovariabelId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KodeId");

                    b.HasIndex("MiljovariabelId");

                    b.ToTable("Trinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Basistrinn", b =>
                {
                    b.HasOne("NiN.Database.Models.LKMKode", "LKMKode")
                        .WithMany("Basistrinn")
                        .HasForeignKey("LKMKodeId");

                    b.Navigation("LKMKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Grunntype", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtype", "Hovedtype")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.GrunntypeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Grunntype", "Grunntype")
                        .WithOne("GrunntypeKode")
                        .HasForeignKey("NiN.Database.Models.GrunntypeKode", "GrunntypeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Grunntype");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtype", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN.Database.Models.HovedtypeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtype", "Hovedtype")
                        .WithOne("HovedtypeKode")
                        .HasForeignKey("NiN.Database.Models.HovedtypeKode", "HovedtypeKeyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtypegruppe", b =>
                {
                    b.HasOne("NiN.Database.Models.Natursystem", "Natursystem")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("NatursystemId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Natursystem");
                });

            modelBuilder.Entity("NiN.Database.Models.HovedtypegruppeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithOne("HovedtypegruppeKode")
                        .HasForeignKey("NiN.Database.Models.HovedtypegruppeKode", "HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN.Database.Models.Kartleggingsenhet", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtype", "Hovedtype")
                        .WithMany("Kartleggingsenheter")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.Miljovariabel", b =>
                {
                    b.HasOne("NiN.Database.Models.Hovedtype", "Hovedtype")
                        .WithMany("Miljovariabler")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.NatursystemKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Natursystem", "Natursystem")
                        .WithOne("NatursystemKode")
                        .HasForeignKey("NiN.Database.Models.NatursystemKode", "NatursystemId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Natursystem");
                });

            modelBuilder.Entity("NiN.Database.Models.Trinn", b =>
                {
                    b.HasOne("NiN.Database.Models.LKMKode", "Kode")
                        .WithMany()
                        .HasForeignKey("KodeId");

                    b.HasOne("NiN.Database.Models.Miljovariabel", "Miljovariabel")
                        .WithMany("Trinn")
                        .HasForeignKey("MiljovariabelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kode");

                    b.Navigation("Miljovariabel");
                });

            modelBuilder.Entity("NiN.Database.Models.Grunntype", b =>
                {
                    b.Navigation("GrunntypeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtype", b =>
                {
                    b.Navigation("HovedtypeKode");

                    b.Navigation("Kartleggingsenheter");

                    b.Navigation("Miljovariabler");

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Hovedtypegruppe", b =>
                {
                    b.Navigation("HovedtypegruppeKode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.LKMKode", b =>
                {
                    b.Navigation("Basistrinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Miljovariabel", b =>
                {
                    b.Navigation("Trinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Natursystem", b =>
                {
                    b.Navigation("NatursystemKode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });
#pragma warning restore 612, 618
        }
    }
}
