// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiN.Database;

namespace NiN.Database.Migrations
{
    [DbContext(typeof(NiNDbContext))]
    partial class NiNContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NiN.Database.Models.Code.Basistrinn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TrinnId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrinnId");

                    b.HasIndex("VersionId");

                    b.ToTable("Basistrinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.LKMKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kode")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("LkmKategori")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("LKMKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.NinKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<string>("KodeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Kode");

                    b.HasDiscriminator<string>("Discriminator").HasValue("NinKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Grunntype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Grunntype");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypegruppeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypegruppeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtypegruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NatursystemId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NatursystemId");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Kartleggingsenhet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<int>("Malestokk")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Kartleggingsenhet");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Miljovariabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HovedtypeId")
                        .HasColumnType("int");

                    b.Property<int?>("KodeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.HasIndex("KodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Miljovariabel");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Natursystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Natursystem");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Trinn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MiljovariabelId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MiljovariabelId");

                    b.HasIndex("VersionId");

                    b.ToTable("Trinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Common.NinVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("NinVersion");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VariasjonKode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definisjon")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VarietyCategory")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("VariasjonKode");

                    b.HasDiscriminator<string>("Discriminator").HasValue("VariasjonKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel0", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel0");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OverordnetKodeId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverordnetKodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel1");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OverordnetKodeId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverordnetKodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel2");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OverordnetKodeId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverordnetKodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel3");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OverordnetKodeId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverordnetKodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel4");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OverordnetKodeId")
                        .HasColumnType("int");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OverordnetKodeId");

                    b.HasIndex("VersionId");

                    b.ToTable("VarietyLevel5");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.BasistrinnKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("BasistrinnId")
                        .HasColumnType("int");

                    b.HasIndex("BasistrinnId")
                        .IsUnique()
                        .HasFilter("[BasistrinnId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("BasistrinnKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.GrunntypeKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("GrunntypeId")
                        .HasColumnType("int");

                    b.HasIndex("GrunntypeId")
                        .IsUnique()
                        .HasFilter("[GrunntypeId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("GrunntypeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.HovedtypeKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("HovedtypeId")
                        .HasColumnType("int");

                    b.HasIndex("HovedtypeId")
                        .IsUnique()
                        .HasFilter("[HovedtypeId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("HovedtypeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.HovedtypegruppeKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("HovedtypegruppeId")
                        .HasColumnType("int");

                    b.HasIndex("HovedtypegruppeId")
                        .IsUnique()
                        .HasFilter("[HovedtypegruppeId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("HovedtypegruppeKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.KartleggingsenhetKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("KartleggingsenhetId")
                        .HasColumnType("int");

                    b.HasIndex("KartleggingsenhetId")
                        .IsUnique()
                        .HasFilter("[KartleggingsenhetId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("KartleggingsenhetKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.NatursystemKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("NatursystemId")
                        .HasColumnType("int");

                    b.HasIndex("NatursystemId")
                        .IsUnique()
                        .HasFilter("[NatursystemId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("NatursystemKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.TrinnKode", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Code.Codes.NinKode");

                    b.Property<int>("TrinnId")
                        .HasColumnType("int");

                    b.HasIndex("TrinnId")
                        .IsUnique()
                        .HasFilter("[TrinnId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("TrinnKode");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel0Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel0Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel1Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("VarietyLevel1Code_VarietyLevelId");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevel1Code_VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel1Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel2Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("VarietyLevel2Code_VarietyLevelId");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevel2Code_VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel2Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel3Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("VarietyLevel3Code_VarietyLevelId");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevel3Code_VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel3Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel4Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("VarietyLevel4Code_VarietyLevelId");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevel4Code_VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel4Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel5Code", b =>
                {
                    b.HasBaseType("NiN.Database.Models.Variety.Codes.VariasjonKode");

                    b.Property<int>("VarietyLevelId")
                        .HasColumnType("int")
                        .HasColumnName("VarietyLevel5Code_VarietyLevelId");

                    b.HasIndex("VarietyLevelId")
                        .IsUnique()
                        .HasFilter("[VarietyLevel5Code_VarietyLevelId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("VarietyLevel5Code");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Basistrinn", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Trinn", "Trinn")
                        .WithMany("Basistrinn")
                        .HasForeignKey("TrinnId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Trinn");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.LKMKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.NinKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Grunntype", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtype", "Hovedtype")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Hovedtype");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtype", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Hovedtypegruppe");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtypegruppe", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Natursystem", "Natursystem")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("NatursystemId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Natursystem");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Kartleggingsenhet", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtype", "Hovedtype")
                        .WithMany("Kartleggingsenheter")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Hovedtype");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Miljovariabel", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtype", "Hovedtype")
                        .WithMany("Miljovariabler")
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Code.Codes.LKMKode", "Kode")
                        .WithMany()
                        .HasForeignKey("KodeId");

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Hovedtype");

                    b.Navigation("Kode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Natursystem", b =>
                {
                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Trinn", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Miljovariabel", "Miljovariabel")
                        .WithMany("Trinn")
                        .HasForeignKey("MiljovariabelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Miljovariabel");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VariasjonKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel0", b =>
                {
                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel1", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel0", "OverordnetKode")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("OverordnetKodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("OverordnetKode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel2", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel1", "OverordnetKode")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("OverordnetKodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("OverordnetKode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel3", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel2", "OverordnetKode")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("OverordnetKodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("OverordnetKode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel4", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel3", "OverordnetKode")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("OverordnetKodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("OverordnetKode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel5", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel4", "OverordnetKode")
                        .WithMany("UnderordnetKoder")
                        .HasForeignKey("OverordnetKodeId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("NiN.Database.Models.Common.NinVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("OverordnetKode");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.BasistrinnKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Basistrinn", "Basistrinn")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.BasistrinnKode", "BasistrinnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basistrinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.GrunntypeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Grunntype", "Grunntype")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.GrunntypeKode", "GrunntypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grunntype");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.HovedtypeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtype", "Hovedtype")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.HovedtypeKode", "HovedtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtype");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.HovedtypegruppeKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.HovedtypegruppeKode", "HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.KartleggingsenhetKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Kartleggingsenhet", "Kartleggingsenhet")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.KartleggingsenhetKode", "KartleggingsenhetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kartleggingsenhet");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.NatursystemKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Natursystem", "Natursystem")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.NatursystemKode", "NatursystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Natursystem");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Codes.TrinnKode", b =>
                {
                    b.HasOne("NiN.Database.Models.Code.Trinn", "Trinn")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Code.Codes.TrinnKode", "TrinnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel0Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel0", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel0Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel1Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel1", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel1Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel2Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel2", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel2Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel3Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel3", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel3Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel4Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel4", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel4Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.Codes.VarietyLevel5Code", b =>
                {
                    b.HasOne("NiN.Database.Models.Variety.VarietyLevel5", "VarietyLevel")
                        .WithOne("Kode")
                        .HasForeignKey("NiN.Database.Models.Variety.Codes.VarietyLevel5Code", "VarietyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VarietyLevel");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Basistrinn", b =>
                {
                    b.Navigation("Kode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Grunntype", b =>
                {
                    b.Navigation("Kode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtype", b =>
                {
                    b.Navigation("Kartleggingsenheter");

                    b.Navigation("Kode");

                    b.Navigation("Miljovariabler");

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Hovedtypegruppe", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Kartleggingsenhet", b =>
                {
                    b.Navigation("Kode");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Miljovariabel", b =>
                {
                    b.Navigation("Trinn");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Natursystem", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Code.Trinn", b =>
                {
                    b.Navigation("Basistrinn");

                    b.Navigation("Kode");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel0", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel1", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel2", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel3", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel4", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();

                    b.Navigation("UnderordnetKoder");
                });

            modelBuilder.Entity("NiN.Database.Models.Variety.VarietyLevel5", b =>
                {
                    b.Navigation("Kode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
